apiVersion: v1
kind: Service
metadata:
  name: main-svc
  # namespace: app
spec:
  ports:
  - name: main-svc
    protocol: TCP
    port: 8081
    targetPort: 8081
  selector:
    app: main
  type: ClusterIP # Можно не писать, по умолчанию